### PR TITLE
Enhance the UI to update the inventory

### PR DESCRIPTION
**Pull request by xuezhou1998**

### CODE REVIEW

**Comment by walkccc** [comment]
You should provide steps in `features/steps/web_steps.py` file.

After running `behave`, you can copy and paste the message and start from there.

**Comment by walkccc** [comment]
Note the difference between 

```
And I set the "Available" to "False"
```

and

```
And I select "True" in the "Available" dropdown
```

**Comment by xuezhou1998** [comment]
> Note the difference between
> 
> ```
> And I set the "Available" to "False"
> ```
> 
> and
> 
> ```
> And I select "True" in the "Available" dropdown
> ```
thank you very much, I modified the scenario

**Comment by walkccc** [comment]
After running `behave`

```
Failing scenarios:
  features/inventory.feature:29  Update an Inventory

0 features passed, 1 failed, 0 skipped
4 scenarios passed, 1 failed, 0 skipped
72 steps passed, 1 failed, 0 skipped, 0 undefined
```

**Comment by xuezhou1998** [comment]
> After running `behave`
> 
> ```
> Failing scenarios:
>   features/inventory.feature:29  Update an Inventory
> 
> 0 features passed, 1 failed, 0 skipped
> 4 scenarios passed, 1 failed, 0 skipped
> 72 steps passed, 1 failed, 0 skipped, 0 undefined
> ```

thank you, i got rid of the sentence of avaiable being false now

**Review by ChingKai5566 — APPROVED** [review]

**Pull request merged**
